services:
    mafiascum.sitechat.listener:
        class: mafiascum\sitechat\event\main_listener
        arguments:
            - '@controller.helper'
            - '@template'
            - '@request'
            - '@user'
        tags:
            - { name: event.listener }