services:
    mafiascum.siteChat.listener:
        class: mafiascum\siteChat\event\main_listener
        arguments:
            - '@controller.helper'
            - '@template'
            - '@request'
            - '@user'
        tags:
            - { name: event.listener }
    mafiascum.siteChat.toggleSiteChatController:
        class: mafiascum\siteChat\controller\toggleSiteChat
        arguments:
            - '@request'
            - '@user'
            - '@dbal.conn'